### ISSUE TITLE
Persistent Storage

### ISSUE THREAD

**Issue by CrusaderW** [CrusaderW/CombatLog#1]
Since I still plan to host the service on AWS as a long-term scalable solution...
We need to get persistant storage going on Fargate instances. Since this not available out of the box, we have to use a library on Docker-level for it...
Useful Links:
https://rexray.readthedocs.io/en/latest/#start-as-a-service
https://github.com/rexray/vg-docker-rexray
https://github.com/rexray/rexray/blob/master/.docs/user-guide/storage-providers/aws.md#aws-ebs

**Comment by CrusaderW** [comment]
fixed for non-aws envs, still needs work to work on AWS...

**Comment by CF-Wilbur** [comment]
Fargate doesn't allow for persistent volumes.  As discussed with @CrusaderW a more sensible approach to AWS architecture would be to use an [AWS DocumentDB](https://docs.aws.amazon.com/documentdb/latest/developerguide/what-is.html).

**Comment by CrusaderW** [comment]
@CF-Wilbur even better, than what I had in mind for a quick-fix. feel free to get going on this. Make a branch, start hacking. I´ll add you as a collab.

**Comment by CrusaderW** [comment]
done
