### ISSUE TITLE
Hardcoded variables to be replaced with envalid

### ISSUE THREAD

**Issue by CF-Wilbur** [CrusaderW/CombatLog#5]
Currently there are several hardcoded variables such as locations of MongoDB, application port bindings and such that should be moved to using [envalid](https://www.npmjs.com/package/envalid) this will allow us to use the same codebase for multiple environments where the env vars are supplied at build/runtime.

**Comment by CrusaderW** [comment]
see #6

**Comment by CrusaderW** [comment]
can this be closed @CF-Wilbur

**Comment by dblane-digicatapult** [comment]
Yes

**Comment by CF-Wilbur** [comment]
Confirmed.
