### ISSUE TITLE
Split front- and backend

### ISSUE THREAD

**Issue by tw1t611** [CrusaderW/CombatLog#9]
## Needs
For the site to go live, we need to seperate front- and backend.
The frontend should be a standard vue web app, that queries the backend.

## Goals
- frontend is standard vue
- backend consists of node services and DocumentDB
- front- and backend development does not depend on each other

**Comment by CrusaderW** [comment]
the requested design is currently met IMO.
the frontend resides in "frontend" and is served in backend/public. The backend resides in "backend".
Not clear yet how I want to do scaling of the application and if it is necessary or even beneficial to separate the two. Need to do further research on the topic and figure out the long term architecture.

**Comment by CrusaderW** [comment]
The backend will be depricated.
I will rebuild the backend as a python - flask server, that will replace all the API calls of the current js backend and provide API endpoints to a desktop client that pushes logs "live"to our system.
We will have 2 new projects:
1. CombatLogGUI
2. CombatLogAPI

**Comment by CrusaderW** [comment]
obsolete due to merge with https://github.com/CrusaderW/CrowfallDashboard
